version: 1.0.{build}
image:
  - Visual Studio 2022
environment:
  matrix:
    - qt: 5.15.2\msvc2019_64
    
install:
- git submodule update --init --recursive 
- set PATH=C:\Qt\%qt%\bin;%PATH%;
- qmake.exe -tp vc -r
build:
  parallel: true
  verbosity: minimal
