version: 1.0.{build}
image:
  - Visual Studio 2022
environment:
  matrix:
    - qt: 5.15.2\msvc2019_64
    
install:
- git submodule update --init --recursive 
- set QTDIR64=C:\Qt\5.15.2\msvc2019_64
- cd installer
- create_installer.bat
build:
  parallel: true
  verbosity: minimal
